#!/bin/bash

whoami=`zenity --entry --title="Bloquear o sistema" --text="Insira nome de usuário:" --width=300`
user=`cat /etc/rc.local | grep rsync | cut --delimiter=' ' --fields=6 | grep $whoami | cut --delimiter='/' --fields=3`
is_success=true
ofris_user=$whoami
is_locked_all=`cat /etc/rc.local | grep rsync`

cd $HOME

gksudo "echo "Password check""
if [[ $? != 0 ]]; then
zenity --error --title="Error" --text="Desculpe, senha errada."
exit
fi

if [[ $whoami = "" ]]; then
exit
fi

if [[ $is_locked_all == "sudo rsync -a --delete /etc/.ofris// /home//" ]]; then
notify-send "Error" "Lamentamos, mas o sistema foi bloqueado para todos os usuários." --icon=error
is_success=false
exit
fi

if [ -d "/home/$whoami" ] && [ $is_success = true ]; then
is_success=true
else
notify-send "Error" "Desculpe , o usuário '$whoami' não existe no seu sistema" --icon=error
is_success=false
fi

grep -v "sudo rsync -a --delete /etc/" /etc/rc.local > ofris_tmp
set $(wc -l ofris_tmp)
ofris_orig=$1
set $(wc -l /etc/rc.local)
ofris_recnt=$1
ofris_rst=$[$ofris_recnt-$ofris_orig]
rm ofris_tmp

if [[ $ofris_rst != 0 ]] && [[ $user == $whoami ]]; then 
notify-send "Error" "Lamentamos, mas o sistema foi bloqueado para o usuário '$whoami'" --icon=error 
is_success=false
elif [ $is_success = true ]; then
grep -v "exit 0" /etc/rc.local > ofris_tmp
echo "sudo rsync -a --delete /etc/.ofris/$ofris_user/ /home/$ofris_user/" >> ofris_tmp
echo "exit 0" >> ofris_tmp
gksudo "rm /etc/rc.local"
gksudo "cp ofris_tmp /etc/rc.local"
rm ofris_tmp
fi

if [ $is_success = true ]; then
if [ -d /etc/.ofris/$ofris_user ]; then
gksudo "rm -r /etc/.ofris/$ofris_user"
fi
if [ -d /etc/.ofris ]; then
gksudo "rsync -a --delete /home/$ofris_user /etc/.ofris/"
else
gksudo "mkdir /etc/.ofris/"
if [[ $ofris_user != "" ]]; then
gksudo "mkdir /etc/.ofris/$ofris_user"
fi
gksudo "rsync -a --delete /home/$ofris_user /etc/.ofris/"
fi
gksudo "chmod +x /etc/rc.local"
fi

if [ $is_success = true ]; then
notify-send "Notificação DeepLock" "Bloqueio para o usuário '$ofris_user' concluída com êxito , reinicie o seu computador para fazer efeito..." --icon=info
fi

exit
