#!/bin/bash

user=`whoami`
is_all=`cat /etc/rc.local | grep rsync | cut --delimiter=' ' --fields=6 | grep $user | cut --delimiter='/' --fields=3`

cd $HOME

gksudo "echo "Password check""
if [[ $? != 0 ]]; then
zenity --error --title="Error" --text="Desculpe, senha errada."
exit
fi

if [[ $is_all == "" ]]; then
open_all=true
enity --error --title="Error" --text="Possibilidades: \n1. O sistema não está bloqueado para '$user'\n2. O sistema está bloqueado para todos os usuários.\n\nSugestão:\n1. Verifique o status, escolhendo 'Show status' no menu do DeepLock"
exit
else
open_all=false
fi

if [ $open_all = false ]; then
grep -v $user /etc/rc.local > ofris_tmp_b
gksudo "rm /etc/rc.local"
gksudo "cp ofris_tmp_b /etc/rc.local"
rm ofris_tmp_b
fi

if [ -d /etc/.ofris/$user ] && [ $open_all = false ]; then
gksudo "rm -r /etc/.ofris/$user"
show_message=true
fi

if [ $show_message = true ]; then
sleep 1
notify-send "Notificação Deeplock" "O sistema foi desbloqueado para o usuário '$user' ..." --icon=info
fi

exit
