#!/bin/bash

whoami=`whoami`
user=`cat /etc/rc.local | grep rsync | cut --delimiter=' ' --fields=6 | grep $whoami | cut --delimiter='/' --fields=3`
is_locked_all=`cat /etc/rc.local | grep rsync`

cd $HOME
grep -v "sudo rsync -a --delete /etc/" /etc/rc.local > ofris_tmp
set $(wc -l ofris_tmp)
ofris_orig=$1
set $(wc -l /etc/rc.local)
ofris_recnt=$1
ofris_rst=$[$ofris_recnt-$ofris_orig]
rm ofris_tmp

if [[ $ofris_rst != 0 ]] && [[ $user == $whoami ]]; then
sleep 1
notify-send "notificação DeepLock" "O sistema está bloqueado para este usuário" --icon=gdu-encrypted-lock
elif [[ $ofris_rst != 0 ]] && [[ $is_locked_all == "sudo rsync -a --delete /etc/.ofris// /home//" ]]; then
sleep 1
notify-send "notificação DeepLock" "O sistema está bloqueado para todos os usuários" --icon=gdu-encrypted-lock
else
sleep 1
notify-send "notificação DeepLock" "O sistema não está bloqueado para esse usuário" --icon=gdu-encrypted-unlock 
fi

exit
